import React, { useState } from 'react';
import {
  Send,
  Plus,
  Search,
  Download,
  Printer,
  FileText,
  Eye,
  CheckCircle2,
  Paperclip
} from 'lucide-react';
import { LetterOut, LetterPriority, LetterOutStatus, MahadId, User } from '../../types';
import { db } from '../../services/db';
import { auth } from '../../services/auth';
import { StatusBadge, PriorityBadge } from '../common/Badges';
import { Modal } from '../common/Modal';
import { EmptyState } from '../common/EmptyState';
import { exportToCSV, printDocument } from '../../services/export';

interface SuratKeluarProps {
  currentUser: User;
  activeMahadId: MahadId;
}

export const SuratKeluar: React.FC<SuratKeluarProps> = ({
  currentUser,
  activeMahadId
}) => {
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [detailLetter, setDetailLetter] = useState<LetterOut | null>(null);

  const letters = db.getLettersOut(activeMahadId);
  const canCreate = auth.hasPermission('letters.out.create');

  // Automatic configured numbering suggestion
  const romanMonths = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'];
  const curMonthRoman = romanMonths[new Date().getMonth()];
  const mahadCode = activeMahadId === 'mahad-banat' ? 'LBT' : 'LBN';
  const autoGeneratedNumber = `${String(letters.length + 1).padStart(3, '0')}/MHD-${mahadCode}/UNIA/${curMonthRoman}/${new Date().getFullYear()}`;

  const [formNomor, setFormNomor] = useState(autoGeneratedNumber);
  const [formTanggal, setFormTanggal] = useState(new Date().toISOString().split('T')[0]);
  const [formTujuan, setFormTujuan] = useState('');
  const [formPerihal, setFormPerihal] = useState('');
  const [formJenis, setFormJenis] = useState('Surat Dinas Pengasuhan');
  const [formSifat, setFormSifat] = useState<LetterPriority>('Biasa');
  const [formIsi, setFormIsi] = useState('');
  const [formPenandatangan, setFormPenandatangan] = useState(
    activeMahadId === 'mahad-banat'
      ? "Nyai Hj. Nurul Hidayah, M.A (Mudir Ma'had Lil Banat)"
      : "K.H. Moh. Khoirul Umam, M.Pd.I (Mudir Ma'had Lil Banin)"
  );
  const [formFileName, setFormFileName] = useState('');

  const filteredLetters = letters.filter(l => {
    const matchSearch =
      l.nomor_surat.toLowerCase().includes(search.toLowerCase()) ||
      l.tujuan.toLowerCase().includes(search.toLowerCase()) ||
      l.perihal.toLowerCase().includes(search.toLowerCase());
    const matchStatus = filterStatus === 'all' || l.status === filterStatus;
    return matchSearch && matchStatus;
  });

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formNomor || !formTujuan || !formPerihal) {
      alert('Lengkapi nomor surat, tujuan, dan perihal.');
      return;
    }

    const targetMahad = activeMahadId === 'all' ? 'mahad-banin' : activeMahadId;

    db.createLetterOut(
      {
        mahad_id: targetMahad,
        nomor_surat: formNomor,
        tanggal: formTanggal,
        tujuan: formTujuan,
        perihal: formPerihal,
        jenis_surat: formJenis,
        sifat: formSifat,
        isi_ringkas: formIsi,
        penandatangan: formPenandatangan,
        lampiran_count: formFileName ? 1 : 0,
        file_name: formFileName || undefined,
        status: 'Draft',
        created_by: currentUser.id
      },
      currentUser
    );

    setIsCreateOpen(false);
    setFormTujuan('');
    setFormPerihal('');
    setFormIsi('');
  };

  const handleUpdateStatus = (letterId: string, newStatus: LetterOutStatus) => {
    db.updateLetterOut(letterId, { status: newStatus }, currentUser);
    if (detailLetter && detailLetter.id === letterId) {
      setDetailLetter({ ...detailLetter, status: newStatus });
    }
  };

  const handleExportCSV = () => {
    exportToCSV(
      `Surat_Keluar_${activeMahadId}_${new Date().toISOString().split('T')[0]}`,
      filteredLetters.map(l => ({
        'No. Surat': l.nomor_surat,
        Tanggal: l.tanggal,
        Tujuan: l.tujuan,
        Perihal: l.perihal,
        Jenis: l.jenis_surat,
        Penandatangan: l.penandatangan,
        Status: l.status
      }))
    );
  };

  const handlePrint = (letter: LetterOut) => {
    printDocument({
      title: letter.perihal,
      documentNumber: letter.nomor_surat,
      mahadName: letter.mahad_id === 'mahad-banat' ? "Ma'had Putri (Lil Banat)" : "Ma'had Putra (Lil Banin)",
      date: letter.tanggal,
      contentHtml: `
        <div style="margin-bottom: 15px;">
          <p>Kepada Yth.<br><strong>${letter.tujuan}</strong><br>di Tempat</p>
        </div>
        <p><em>Assalamu'alaikum Wr. Wb.</em></p>
        <div style="text-align: justify; margin: 15px 0;">
          <p>${letter.isi_ringkas || 'Dengan ini disampaikan pemberitahuan resmi berkenaan dengan agenda kepesantrenan di lingkungan Ma’had Universitas Al-Amien Prenduan.'}</p>
        </div>
        <p>Demikian surat ini kami sampaikan, atas perhatian dan kerja samanya diucapkan terima kasih.</p>
        <p><em>Wassalamu'alaikum Wr. Wb.</em></p>
      `,
      signatoryName: letter.penandatangan,
      signatoryTitle: "Mudir Ma'had"
    });
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Send className="w-6 h-6 text-[#0d5c3a]" />
            Administrasi Surat Keluar
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Penerbitan surat dinas, penomoran otomatis terkonfigurasi, penandatanganan, dan pengarsipan
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            onClick={handleExportCSV}
            className="inline-flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 shadow-xs"
          >
            <Download className="w-4 h-4 text-slate-500" />
            Export Excel/CSV
          </button>

          {canCreate && (
            <button
              type="button"
              onClick={() => {
                setFormNomor(autoGeneratedNumber);
                setIsCreateOpen(true);
              }}
              className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-white bg-[#0d5c3a] hover:bg-[#09472c] rounded-lg transition-colors shadow-xs"
            >
              <Plus className="w-4 h-4" />
              Buat Surat Keluar
            </button>
          )}
        </div>
      </div>

      {/* Filter Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-col md:flex-row gap-3 items-center justify-between">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-400" />
          <input
            type="text"
            placeholder="Cari nomor surat, tujuan, perihal..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 text-xs rounded-lg border border-slate-200 focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20"
          />
        </div>

        <select
          value={filterStatus}
          onChange={e => setFilterStatus(e.target.value)}
          className="px-3 py-1.5 text-xs rounded-lg border border-slate-200 bg-white text-slate-700 focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20"
        >
          <option value="all">Semua Status</option>
          <option value="Draft">Draft</option>
          <option value="Diproses">Diproses</option>
          <option value="Menunggu Tanda Tangan">Menunggu Tanda Tangan</option>
          <option value="Selesai">Selesai</option>
          <option value="Diarsipkan">Diarsipkan</option>
        </select>
      </div>

      {/* Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-700">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 font-semibold uppercase tracking-wider text-[11px]">
              <tr>
                <th className="px-4 py-3">Nomor Surat</th>
                <th className="px-4 py-3">Tanggal</th>
                <th className="px-4 py-3">Tujuan</th>
                <th className="px-4 py-3">Perihal & Jenis</th>
                <th className="px-4 py-3">Penandatangan</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Aksi</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredLetters.length === 0 ? (
                <tr>
                  <td colSpan={7} className="p-8 text-center">
                    <EmptyState
                      icon={Send}
                      title="Belum ada surat keluar"
                      description="Belum ada catatan surat keluar. Klik 'Buat Surat Keluar' untuk menerbitkan dokumen baru."
                    />
                  </td>
                </tr>
              ) : (
                filteredLetters.map(letter => (
                  <tr key={letter.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-4 py-3 font-mono font-bold text-slate-800 whitespace-nowrap">
                      {letter.nomor_surat}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">{letter.tanggal}</td>
                    <td className="px-4 py-3 font-medium text-slate-800 max-w-[180px] truncate">
                      {letter.tujuan}
                    </td>
                    <td className="px-4 py-3 max-w-xs">
                      <div className="font-semibold text-slate-800 line-clamp-1">{letter.perihal}</div>
                      <div className="text-[11px] text-slate-400">{letter.jenis_surat}</div>
                    </td>
                    <td className="px-4 py-3 max-w-[160px] truncate text-slate-600">
                      {letter.penandatangan}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <StatusBadge status={letter.status} size="sm" />
                    </td>
                    <td className="px-4 py-3 text-right whitespace-nowrap space-x-1">
                      <button
                        type="button"
                        onClick={() => setDetailLetter(letter)}
                        className="p-1.5 text-slate-500 hover:text-slate-800 hover:bg-slate-100 rounded-md"
                        title="Lihat Detail"
                      >
                        <Eye className="w-4 h-4" />
                      </button>
                      <button
                        type="button"
                        onClick={() => handlePrint(letter)}
                        className="p-1.5 text-slate-500 hover:text-slate-800 hover:bg-slate-100 rounded-md"
                        title="Cetak Surat Resmi"
                      >
                        <Printer className="w-4 h-4" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* MODAL BUAT SURAT KELUAR */}
      <Modal
        isOpen={isCreateOpen}
        onClose={() => setIsCreateOpen(false)}
        title="Penerbitan Surat Keluar"
        subtitle="Nomor surat otomatis sesuai standar tata naskah dinas UNIA"
        maxWidth="2xl"
      >
        <form onSubmit={handleCreateSubmit} className="space-y-4 text-xs">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block font-semibold text-slate-700 mb-1">Nomor Surat Dinas *</label>
              <input
                type="text"
                required
                value={formNomor}
                onChange={e => setFormNomor(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 font-mono focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">Tanggal Surat *</label>
              <input
                type="date"
                required
                value={formTanggal}
                onChange={e => setFormTanggal(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block font-semibold text-slate-700 mb-1">Tujuan / Kepada Yth. *</label>
              <input
                type="text"
                required
                placeholder="cth: Para Koordinator Asrama Ma’had"
                value={formTujuan}
                onChange={e => setFormTujuan(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20"
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">Jenis Surat</label>
              <select
                value={formJenis}
                onChange={e => setFormJenis(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-slate-300 bg-white"
              >
                <option value="Surat Undangan Dinas">Surat Undangan Dinas</option>
                <option value="Surat Edaran">Surat Edaran</option>
                <option value="Surat Tugas">Surat Tugas</option>
                <option value="Surat Keterangan">Surat Keterangan</option>
                <option value="Surat Pengantar">Surat Pengantar</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Perihal Surat *</label>
            <input
              type="text"
              required
              placeholder="cth: Undangan Musyawarah Rencana Kerja Kepesantrenan"
              value={formPerihal}
              onChange={e => setFormPerihal(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300 focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20 font-medium"
            />
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Pejabat Penandatangan *</label>
            <input
              type="text"
              required
              value={formPenandatangan}
              onChange={e => setFormPenandatangan(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300"
            />
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Isi / Ringkasan Surat</label>
            <textarea
              rows={4}
              placeholder="Uraikan isi pemberitahuan atau pesan dinas..."
              value={formIsi}
              onChange={e => setFormIsi(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300 focus:outline-none focus:ring-2 focus:ring-[#0d5c3a]/20"
            />
          </div>

          <div>
            <label className="block font-semibold text-slate-700 mb-1">Berkas Lampiran (Opsional)</label>
            <input
              type="text"
              placeholder="cth: Lampiran_Jadwal_Kegiatan.pdf"
              value={formFileName}
              onChange={e => setFormFileName(e.target.value)}
              className="w-full px-3 py-2 rounded-lg border border-slate-300"
            />
          </div>

          <div className="flex items-center justify-end gap-2 pt-4 border-t border-slate-200">
            <button
              type="button"
              onClick={() => setIsCreateOpen(false)}
              className="px-4 py-2 text-xs font-medium text-slate-600 hover:bg-slate-100 rounded-lg"
            >
              Batal
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-xs font-semibold text-white bg-[#0d5c3a] hover:bg-[#09472c] rounded-lg shadow-xs"
            >
              Terbitkan Draf Surat
            </button>
          </div>
        </form>
      </Modal>

      {/* DETAIL MODAL */}
      <Modal
        isOpen={!!detailLetter}
        onClose={() => setDetailLetter(null)}
        title="Detail Surat Keluar"
        subtitle={detailLetter?.nomor_surat}
        maxWidth="lg"
      >
        {detailLetter && (
          <div className="space-y-4 text-xs">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <span className="font-mono text-slate-600">{detailLetter.nomor_surat}</span>
                <StatusBadge status={detailLetter.status} />
              </div>
              <h4 className="text-sm font-bold text-slate-800">{detailLetter.perihal}</h4>
              <p className="text-slate-600">Kepada: {detailLetter.tujuan}</p>
            </div>

            <div className="grid grid-cols-2 gap-3 text-slate-700">
              <div>
                <span className="text-slate-400 block text-[11px]">Tanggal Terbit</span>
                <span className="font-medium">{detailLetter.tanggal}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-[11px]">Jenis Dokumen</span>
                <span className="font-medium">{detailLetter.jenis_surat}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-[11px]">Penandatangan</span>
                <span className="font-medium">{detailLetter.penandatangan}</span>
              </div>
              <div>
                <span className="text-slate-400 block text-[11px]">Sifat</span>
                <PriorityBadge priority={detailLetter.sifat} />
              </div>
            </div>

            <div>
              <span className="text-slate-400 block text-[11px] mb-1">Isi Dokumen</span>
              <p className="p-3 bg-slate-50 rounded-lg border border-slate-200 text-slate-800 leading-relaxed whitespace-pre-line">
                {detailLetter.isi_ringkas || 'Tidak ada uraian.'}
              </p>
            </div>

            {/* Workflow status advance */}
            <div className="p-3 bg-slate-100 rounded-lg flex items-center justify-between">
              <span className="font-medium text-slate-700">Perbarui Status Alur Dokumen:</span>
              <div className="flex gap-1.5 flex-wrap">
                {detailLetter.status === 'Draft' && (
                  <button
                    type="button"
                    onClick={() => handleUpdateStatus(detailLetter.id, 'Diproses')}
                    className="px-2.5 py-1 bg-blue-600 text-white font-medium rounded hover:bg-blue-700 text-xs"
                  >
                    Proses
                  </button>
                )}
                {detailLetter.status === 'Diproses' && (
                  <button
                    type="button"
                    onClick={() => handleUpdateStatus(detailLetter.id, 'Menunggu Tanda Tangan')}
                    className="px-2.5 py-1 bg-amber-600 text-white font-medium rounded hover:bg-amber-700 text-xs"
                  >
                    Ajukan Tanda Tangan
                  </button>
                )}
                {detailLetter.status === 'Menunggu Tanda Tangan' && (
                  <button
                    type="button"
                    onClick={() => handleUpdateStatus(detailLetter.id, 'Selesai')}
                    className="px-2.5 py-1 bg-emerald-600 text-white font-medium rounded hover:bg-emerald-700 text-xs"
                  >
                    Tandatangani & Selesai
                  </button>
                )}
                {detailLetter.status === 'Selesai' && (
                  <button
                    type="button"
                    onClick={() => handleUpdateStatus(detailLetter.id, 'Diarsipkan')}
                    className="px-2.5 py-1 bg-slate-700 text-white font-medium rounded hover:bg-slate-800 text-xs"
                  >
                    Arsipkan
                  </button>
                )}
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-3 border-t border-slate-200">
              <button
                type="button"
                onClick={() => handlePrint(detailLetter)}
                className="px-4 py-2 text-xs font-semibold text-white bg-[#0d5c3a] hover:bg-[#09472c] rounded-lg flex items-center gap-1.5"
              >
                <Printer className="w-3.5 h-3.5" />
                Cetak Format Resmi Kop UNIA
              </button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};
